create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  role text not null default 'member' check (role in ('member', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  account_id bigint not null unique,
  steam_id64 text not null unique,
  personaname text not null,
  avatar_url text,
  roles text[] not null default '{}',
  stats jsonb,
  stats_fetched_at timestamptz,
  added_by uuid references public.users(id) on delete set null,
  added_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.players add column if not exists stats jsonb;
alter table public.players add column if not exists stats_fetched_at timestamptz;
alter table public.players add column if not exists roles text[] not null default '{}';
alter table public.players add column if not exists rating_overrides jsonb;

alter table public.users enable row level security;
alter table public.players enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
security definer set search_path = public
stable
as $$
  select exists (select 1 from public.users where id = auth.uid() and role = 'admin');
$$;

drop policy if exists "Users can read their own profile" on public.users;
drop policy if exists "Admins can read users" on public.users;
drop policy if exists "Admins can change user roles" on public.users;
drop policy if exists "Signed in users can read players" on public.players;
drop policy if exists "Admins can insert players" on public.players;
drop policy if exists "Admins can update players" on public.players;
drop policy if exists "Admins can delete players" on public.players;

create policy "Users can read their own profile"
  on public.users for select using (auth.uid() = id);

create policy "Admins can read users"
  on public.users for select to authenticated
  using (auth.uid() = id or public.is_admin());

create policy "Admins can change user roles"
  on public.users for update to authenticated
  using (public.is_admin())
  with check (role in ('member', 'admin'));

create or replace function public.prevent_last_admin_removal()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  if old.role = 'admin' and new.role = 'member'
     and not exists (select 1 from public.users where role = 'admin' and id <> old.id) then
    raise exception 'Нельзя удалить последнего администратора';
  end if;
  return new;
end;
$$;

drop trigger if exists protect_last_admin on public.users;
create trigger protect_last_admin
  before update of role on public.users
  for each row execute procedure public.prevent_last_admin_removal();

drop policy if exists "Signed in users can read players" on public.players;
drop policy if exists "Anyone can read players" on public.players;

create policy "Anyone can read players"
  on public.players for select to anon, authenticated using (true);

create policy "Admins can insert players"
  on public.players for insert to authenticated
  with check (public.is_admin());

create policy "Admins can update players"
  on public.players for update to authenticated
  using (public.is_admin());

create policy "Admins can delete players"
  on public.players for delete to authenticated
  using (public.is_admin());

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.users (id, email, display_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.email),
    case when not exists (select 1 from public.users) then 'admin' else 'member' end
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Make the oldest existing account an admin when this schema is applied to an
-- already-used project that has no administrator yet.
update public.users
set role = 'admin'
where id = (
  select id from public.users order by created_at limit 1
)
and not exists (select 1 from public.users where role = 'admin');
